[env:lilygo-t-can485]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/embed_web.py

; LilyGo T-CAN485 (ESP32-WROOM, 4MB flash, no PSRAM)
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 40000000L
board_build.partitions = huge_app.csv   ; no OTA/filesystem needed, gives ~3MB app space

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^7
    adafruit/Adafruit NeoPixel@^1.12.3
